/* Generated By:JavaCC: Do not edit this line. LexerConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface LexerConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int LPAREN = 6;
  /** RegularExpression Id. */
  int RPAREN = 7;
  /** RegularExpression Id. */
  int LBRACE = 8;
  /** RegularExpression Id. */
  int RBRACE = 9;
  /** RegularExpression Id. */
  int ENDEXP = 10;
  /** RegularExpression Id. */
  int EQ = 11;
  /** RegularExpression Id. */
  int VAR = 12;
  /** RegularExpression Id. */
  int TYPE = 13;
  /** RegularExpression Id. */
  int BOOL = 14;
  /** RegularExpression Id. */
  int ID = 15;
  /** RegularExpression Id. */
  int ARRAY = 16;
  /** RegularExpression Id. */
  int STR = 17;
  /** RegularExpression Id. */
  int CHAR = 18;
  /** RegularExpression Id. */
  int NUM = 19;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 5>",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\";\"",
    "\"=\"",
    "\"var\"",
    "<TYPE>",
    "<BOOL>",
    "<ID>",
    "<ARRAY>",
    "<STR>",
    "<CHAR>",
    "<NUM>",
    "\":\"",
    "\",\"",
  };

}
